
# Context generated by the InputFilesStep and read by Stade Selection, Artifact Selection and Group Definition
context_files_event_names = "files_event_names"

# Context generated by Stade Selection and read by Group Definition
# Checkable model
context_stage_check_model = "stages_events_model"

# Context generated by Artifact Selection and read by Group Definition
# Checkable model
context_artifact_check_model = "artifact_events_model"

# Context generated by Group Definition and read by Stage Selection and Artifact Selection
# Editable model
context_editable_model = "group_editable_model"