# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file ''
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QSizePolicy, QTextEdit, QVBoxLayout, QWidget)
from . import imgs
from . import hist_freq_transition_rc
import themes_rc

class Ui_SSWCIntroStep(object):
    def setupUi(self, SSWCIntroStep):
        if not SSWCIntroStep.objectName():
            SSWCIntroStep.setObjectName(u"SSWCIntroStep")
        SSWCIntroStep.resize(1052, 822)
        self.verticalLayout = QVBoxLayout(SSWCIntroStep)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.text_layout = QVBoxLayout()
        self.text_layout.setObjectName(u"text_layout")
        self.image_hist = QLabel(SSWCIntroStep)
        self.image_hist.setObjectName(u"image_hist")
        self.image_hist.setLineWidth(0)
        self.image_hist.setPixmap(QPixmap(u":/hist/transition_frequency.png"))
        self.image_hist.setAlignment(Qt.AlignCenter)

        self.text_layout.addWidget(self.image_hist)

        self.title_label = QLabel(SSWCIntroStep)
        self.title_label.setObjectName(u"title_label")
        self.title_label.setScaledContents(True)
        self.title_label.setWordWrap(True)

        self.text_layout.addWidget(self.title_label)

        self.textEdit = QTextEdit(SSWCIntroStep)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setFrameShape(QFrame.NoFrame)
        self.textEdit.setLineWidth(0)
        self.textEdit.setReadOnly(True)

        self.text_layout.addWidget(self.textEdit)


        self.horizontalLayout.addLayout(self.text_layout)


        self.verticalLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(SSWCIntroStep)

        QMetaObject.connectSlotsByName(SSWCIntroStep)
    # setupUi

    def retranslateUi(self, SSWCIntroStep):
        SSWCIntroStep.setWindowTitle("")
        SSWCIntroStep.setStyleSheet(QCoreApplication.translate("SSWCIntroStep", u"font: 12pt \"Roboto\";", None))
        self.image_hist.setText("")
        self.title_label.setText(QCoreApplication.translate("SSWCIntroStep", u"<html><head/><body><p><span style=\" font-weight:600;\">Slow Wave Classifier</span></p></body></html>", None))
        self.textEdit.setHtml(QCoreApplication.translate("SSWCIntroStep", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Roboto'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool classifies slow waves into categories based on their transition frequency.  </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">1- Input file :</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent"
                        ":0px;\">	The classifier uses the files generated by the tool Slow Wave Detection within Snooz.<br />	Add the slow wave characteristics files, the slow wave cohort report and the sleep stages files for your cohort.<br />	The slow wave characteristics files are saved in a directory at the cohort report level named &quot;<span style=\" color:#000000;\">slow_waves_characteristics&quot;.<br />	The sleep stages files </span>are saved in a directory at the cohort report level named &quot;slow_wave_sleep_stages<span style=\" color:#000000;\">&quot;.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">2- Classification criteria : </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">	Two options are avaible:</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-bloc"
                        "k-indent:0; text-indent:0px;\">	1. An automatic classification.<br />	Automatic classification using a gaussian mixture to fit the distribution of sleep slow waves transition frequency and <br />	checking the Akaire Information Criterion (AIC) of each model to select the gaussian distribution that fit's the best. <br />	In other words, the gaussian mixture distribution that has the lowest AIC value is the one that determines <br />	the number of sleep slow wave categories that are present in the dataset.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">	2. A manual classification.<br />	Specify the number of sleep slow waves categories to use.<br />	<span style=\" font-style:italic;\">* Useful if the automatic classification doesn't analyse correctly the dataset or <br />	if you already know how many sleep slow wave categories there are in the set. <br />	For example, you can select an automatic classification for a group data an"
                        "lysis to find out <br />	the number of sleep slow wave categories you will apply to each individual if an individual analysis is needed.</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" text-decoration: underline;\">3-Output Files :</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">	Choose the destination folder for the output files.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">	The slow wave characteristics files are copied and saved in the output directory, with the corresponding slow wave category appended.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">	A cohort report containing the averaged slow wave characteristics per category is generated.<br />	"
                        "The slow wave characteristics are also provided per sleep cycle and segment of night.<br />	Choose the granularity of the segment you are interested in. </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">	The histogram of transition frequency values along with the resulting model is saved in the output directory as a .pdf picture. </p></body></html>", None))
    # retranslateUi

